CREATE TABLE Automobil(
IdA INTEGER PRIMARY KEY,
RegBr INTEGER UNIQUE,
IdM INTEGER,
CONSTRAINT fk_Model
FOREIGN KEY (IdM) 
REFERENCES Model(IdM)
);

CREATE TABLE Nabavka(
IdN INTEGER PRIMARY KEY,
DatumVreme date,
IdA INTEGER,
IdD INTEGER,
CONSTRAINT fk_Automobil
FOREIGN KEY (IdA) 
REFERENCES Automobil(IdA),
CONSTRAINT fk_Dobavljac
FOREIGN KEY (IdD) 
REFERENCES Dobavljac(IdD)
);

CREATE TABLE Kupovina(
IdKup INTEGER PRIMARY KEY,
DatumVreme date,
Cena DOUBLE,
IdA INTEGER,
IdK INTEGER,
CONSTRAINT fk_Automobil
FOREIGN KEY (IdA) 
REFERENCES Automobil(IdA),
CONSTRAINT fk_Kupac
FOREIGN KEY (IdK) 
REFERENCES Kupac(IdK)
);


CREATE TABLE Model(
IdM INTEGER PRIMARY KEY,
 Model VARCHAR(30) NOT NULL,
 Marka VARCHAR(30) NOT NULL,
 BrProdatih INTEGER,
 BrNabavljenih INTEGER,
 Profit DOUBLE
);

CREATE TABLE Kupac(
IdK INTEGER PRIMARY KEY,
 Ime VARCHAR(30) NOT NULL,
 Prezime VARCHAR(30) NOT NULL,
 BrLK INTEGER,
 BrKupljenih INTEGER
);

CREATE TABLE Dobavljac(
IdD INTEGER PRIMARY KEY,
 Naziv VARCHAR(30) NOT NULL,
 BrDobavljenih INTEGER
);